# Generated by Django 4.0.4 on 2022-06-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('skills_list', models.TextField()),
                ('softwares_list', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='images/wu.jpg', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='python.jpg', upload_to='images/'),
        ),
    ]
