# Generated by Django 4.0.4 on 2022-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepage_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200)),
                ('para', models.TextField()),
                ('para2', models.TextField()),
                ('skills', models.TextField()),
                ('softwares', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='images/wu.jpg', upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
