# Generated by Django 4.0.4 on 2022-06-30 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_index_delete_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogs',
        ),
    ]
