# Generated by Django 4.0.4 on 2022-06-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_blog_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='images/python.jpg', upload_to='images/'),
        ),
    ]
