# Generated by Django 4.0.4 on 2022-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='paragraph',
            field=models.CharField(default='fndjkfkjdfkjdjkfkjdsfkjdsfjdsfjkdsjf', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='images/wu.jpg', upload_to='images/'),
        ),
    ]
